#!/usr/bin/env python3
# Concept: Mukesh Kesharwani
# Contact: mukesh.kesharwani@adobe.com
"""Write monitoring_dashboard/_version.py from VERSION file and git HEAD."""

from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "monitoring_dashboard" / "_version.py"
REPO_URL = "https://github.com/keekar2022/Security_Monitoring"


def _read_semver() -> str:
    vf = ROOT / "VERSION"
    if vf.is_file():
        for line in vf.read_text(encoding="utf-8").splitlines():
            if line.strip().startswith("VERSION="):
                return line.split("=", 1)[1].strip()
    return "0.0.0"


def _git(cmd: list[str]) -> str:
    try:
        return subprocess.check_output(cmd, cwd=ROOT, stderr=subprocess.DEVNULL, text=True).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def main() -> int:
    sha_full = _git(["git", "rev-parse", "HEAD"])
    sha_short = _git(["git", "rev-parse", "--short", "HEAD"]) or "unknown"
    branch = _git(["git", "rev-parse", "--abbrev-ref", "HEAD"]) or "unknown"
    base = _read_semver()
    version = f"{base}+{sha_short}"
    build_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    commit_url = f"{REPO_URL}/commit/{sha_full}" if sha_full else REPO_URL
    OUT.write_text(
        f'''# Auto-generated by scripts/write_version.py — do not edit.
__version__ = "{version}"
__git_sha__ = "{sha_short}"
__git_branch__ = "{branch}"
__build_time_utc__ = "{build_time}"
__repo_url__ = "{REPO_URL}"
__commit_url__ = "{commit_url}"
''',
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
