# Auto-generated by scripts/write_version.py — do not edit.
__version__ = "1.1.4+9a08549"
__git_sha__ = "9a08549"
__git_branch__ = "main"
__build_time_utc__ = "2026-05-18T21:10:58Z"
__repo_url__ = "https://github.com/keekar2022/Security_Monitoring"
__commit_url__ = "https://github.com/keekar2022/Security_Monitoring/commit/9a08549b7e7547211e660c1288b3b861f1683d56"
