# Auto-generated by scripts/write_version.py — do not edit.
__version__ = "1.1.3+cccbc21"
__git_sha__ = "cccbc21"
__git_branch__ = "main"
__build_time_utc__ = "2026-05-18T21:04:48Z"
__repo_url__ = "https://github.com/keekar2022/Security_Monitoring"
__commit_url__ = "https://github.com/keekar2022/Security_Monitoring/commit/cccbc210a50cd0cb35155ced393f047f6207948f"
